services:
  reverse_proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /sas/INT222/int222_reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - /sas/INT222/int222_reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
      - /sas/certificateFiles:/certificateFiles
    networks:
      network-kw2:
       ipv4_address: 172.19.21.2
  back:
    image: openjdk:17-jdk-alpine
    working_dir: /app
    command: sh -c "./mvnw clean package && java -jar ./target/*.jar"
    ports:
      - "8080:8080"
    depends_on:
      - "dbserver"
    volumes:
      - /sas/INT222/int222_backend:/app
    environment:
      - mysql_user=root
      - mysql_password=12345678
      - mysql_url=dbserver
    restart: on-failure
    networks:
      network-kw2:
       ipv4_address: 172.19.21.3
  dbserver:
    image: mysql:8.0.33
    volumes:
      - /sas/INT222/int222_database:/docker-entrypoint-initdb.d
      - /sas/INT222/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=dev1
      - MYSQL_PASSWORD=x_eRT2vv4
      - MYSQL_DATABASE=SAS
      - LANG=en_US.UTF-8
    networks:
      network-kw2:
       ipv4_address: 172.19.21.4
  front:
    image: frontend:124.4
    build:
      context: /sas/INT222/
      dockerfile: int222_dockerfiles/dockerfile_frontend 
    ports:
      - "5173:5173"
    networks:
      network-kw2:
       ipv4_address: 172.19.21.5
networks:
    network-kw2:
     ipam:
      config: 
        - subnet: 172.19.21.0/16
